CREATE DATABASE BANCOTCC;
USE BANCOTCC; 

CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(35) NOT NULL,
    SOBRENOME VARCHAR(50) NOT NULL,
    SENHA VARCHAR(200) NOT NULL,
    EMAIL_LOGIN VARCHAR(64) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF VARCHAR(14) NULL,
    ENDERECO VARCHAR(55) NOT NULL,
    N_RESIDENCIAL INT NOT NULL,
    BAIRRO VARCHAR(20) NOT NULL,
    COMPLEMENTO_RESI VARCHAR(15),
    CEP VARCHAR(9) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    SEXO NVARCHAR(20) NOT NULL CHECK (SEXO IN ('Feminino', 'Masculino', 'Prefiro não declarar')),
    CONF_SENHA VARCHAR(200) NOT NULL,
	STATUS_ROLE NVARCHAR(20) CHECK (STATUS_ROLE IN('CLIENTE','PRESTADOR','ADMINISTRADOR')),
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE SERVICO (
    ID_SERV INT IDENTITY(1,1) PRIMARY KEY,
    NOME_SERVICO VARCHAR(45),
    DESCRICAO_SERVICO VARCHAR(200),
    ID_CATEGORIA INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);


CREATE TABLE PRESTADOR (
    ID_USUARIO INT PRIMARY KEY,
    NOME_COMERCIAL VARCHAR(80) NOT NULL,
    CNPJ VARCHAR(18)  NULL,
	TIPO_PRESTADOR NVARCHAR(20) CHECK (TIPO_PRESTADOR IN('AUTONOMO','MICROEMPREENDEDOR')),
	ID_CATEGORIA INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
);

CREATE TABLE PRESTADOR_SERV (
    ID_USUARIO INT,
    ID_SERV INT,
	PRIMARY KEY (ID_USUARIO, ID_SERV),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SERV) REFERENCES SERVICO(ID_SERV)
);



CREATE TABLE AGENDAMENTO (
    ID_AGENDAMENTO INT IDENTITY(1,1) PRIMARY KEY,
    DT_AGENDAMENTO DATE NOT NULL,
    HR_AGENDAMENTO TIME NOT NULL,
    VL_ORC DECIMAL(10, 2) NOT NULL
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
	STATUS_SERVICO NVARCHAR(20) CHECK (STATUS_SERVICO IN('CONCLUIDO','PENDENTE','CANCELADO')),
    CATEGORIA_PEDIDO VARCHAR(20) NOT NULL,
    DESCRICAO_PEDIDO VARCHAR(90) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_AGENDAMENTO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_AGENDAMENTO) REFERENCES AGENDAMENTO(ID_AGENDAMENTO)
);

CREATE TABLE AGENDA (
    ID_AGENDA INT IDENTITY(1,1) PRIMARY KEY,
    HR_DISPONIVEL TIME NOT NULL,
    HR_INDISPONIVEL TIME NOT NULL,
    DIA_SERV DATE NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE AVALIACAO (
    ID_AVALIACAO INT IDENTITY(1,1) PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    COMENTARIOS VARCHAR(80),
    NOTA INT NOT NULL CHECK (NOTA BETWEEN 0 AND 5), 
    DT_AVALIACAO DATETIME NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
);

CREATE TABLE CONTRATO (
    ID_CONTRATO INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    PER_TAXA DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	DATA_ACEITE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PAGAMENTO (
    ID_PGT INT IDENTITY(1,1) PRIMARY KEY,
    VL_TAXA DECIMAL(10, 2) NOT NULL,
	FORMA_PGT NVARCHAR(20) CHECK (FORMA_PGT IN('PIX','CARTAO DEBITO','CARTAO CREDITO')),
    DATA_PG DATETIME NOT NULL,
    ID_CONTRATO INT NOT NULL,
    FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO(ID_CONTRATO)
);

CREATE TABLE POSTAGEM (
    ID_POSTAGEM INT IDENTITY(1,1) PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    DESCRICAO_POST VARCHAR(255),
    RESOLUCAO VARCHAR(50),
    TIPO_ARQUIVO VARCHAR(10),
    DT_POSTAGEM DATETIME NOT NULL DEFAULT GETDATE(), 
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CHAT (
    ID_CHAT INT IDENTITY(1,1) PRIMARY KEY,
	MESSAGEM_CHAT VARCHAR(255) NOT NULL,
    TIMESTAMP DATETIME DEFAULT GETDATE(),
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Insert das categorias

INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Assistência Técnica');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Aulas');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Reformas e Reparos');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Serviços Domésticos');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Eventos');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Saúde');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Serviços Gerais');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Transporte');
INSERT INTO CATEGORIA (NOME_CATEGORIA) VALUES ('Moda e Beleza');


--assistencia tecnica 
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Televisão', 'Conserto e instalação de televisores.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Ar Condicionado', 'Instalação e manutenção de ar condicionados.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Aparelho de Som', 'Conserto e instalação de sistemas de som.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('DVD / Blu-Ray', 'Conserto e instalação de players de DVD e Blu-Ray.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Home Theater', 'Instalação e conserto de sistemas de home theater.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Vídeo Game', 'Conserto de consoles de videogame.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Câmera', 'Conserto de câmeras fotográficas e filmadoras.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Aquecedor a Gás', 'Instalação e conserto de aquecedores a gás.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Lava Roupa', 'Serviço de conserto e instalação de máquinas de lavar roupa.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Geladeira e Freezer', 'Manutenção e instalação de geladeiras e freezers.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Fog o e Cooktop', 'Conserto e instalação de fogões e cooktops.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Micro-ondas', 'Conserto e instalação de micro-ondas.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Lava-Lou a', 'Conserto e instalação de m quinas de lavar lou a.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de M quina de Costura', 'Conserto e instalação de m quinas de costura.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Adega Climatizada', 'Conserto e instalação de adegas climatizadas.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Secadora de Roupas', 'Instalação e conserto de secadoras de roupas.', 1);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Conserto/Instalação de Cabeamento de Redes', 'Manutenção e instalação de cabeamentos de redes.', 1);

-- AULAS
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Idiomas', 'Aulas de idiomas como inglês, espanhol, entre outros.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Escolares e Reforço', 'Aulas de reforço para estudantes de várias disciplinas.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Concursos', 'Preparação para concursos públicos e exames de seleção.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Pré-Vestibular', 'Aulas para preparar candidatos para vestibulares.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Ensino Superior', 'Aulas de disciplinas de nível superior.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Educação Especial', 'Aulas adaptadas para alunos com necessidades especiais.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Ensino Profissionalizante', 'Cursos profissionalizantes e técnico.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Saúde', 'Aulas sobre saúde e bem-estar.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Tarefas', 'Auxílio em tarefas escolares e acadêmicas.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Música', 'Aulas de música e instrumentos.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Artes', 'Aulas de várias formas de arte.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Bem-Estar', 'Atividades que promovem o bem-estar.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Artesanato', 'Aulas de técnicas de artesanato.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('TV e Teatro', 'Aulas sobre atuação e produção audiovisual.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Circo', 'Aulas sobre técnicas circenses.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Beleza', 'Aulas sobre estética e cuidados pessoais.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Paisagismo', 'Aulas sobre design de jardins e espaços externos.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Moda', 'Aulas sobre moda e tendências.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Fotografia', 'Aulas sobre técnicas de fotografia.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Esportes', 'Aulas de diferentes modalidades esportivas.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Dança', 'Aulas de dança de diferentes estilos.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Luta', 'Aulas de artes marciais e defesa pessoal.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Lazer', 'Atividades de lazer e recreação.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Jogos', 'Aulas sobre jogos e dinâmicas.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Informática', 'Aulas de informática e tecnologia.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Esportes Eletrônicos', 'Aulas sobre jogos eletrônicos competitivos.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Desenvolvimento Web', 'Aulas sobre criação e desenvolvimento de sites.', 2);
INSERT INTO SERVICO (NOME_SERVICO, DESCRICAO_SERVICO, ID_CATEGORIA) VALUES ('Marketing Digital', 'Aulas sobre estratégias de marketing online.', 2);

